{% set name = "robotframework-lsp" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robotframework-lsp-{{ version }}.tar.gz
  sha256: f1bf57ef567c817d9040c541a2128fd21f92fac1ac543d4f9ad2eeecafcf662e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - robotframework_ls = robotframework_ls.__main__:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - robotframework >=3.2
  run_constrained:
    - robotframework-seleniumlibary >=4.4

test:
  requires:
    - pip
  imports:
    - robotframework_debug_adapter
    - robotframework_ls.vendored.robocorp_ls_core

  commands:
    - python -m pip check
    - robotframework_ls --version
    - robotframework_ls --help

about:
  home: https://github.com/robocorp/robotframework-lsp
  summary: Language Server Protocol implementation for Robot Framework
  license: Apache-2.0
  license_file:
    - COPYRIGHT
    - LICENSE
    - ThirdPartyNotices.txt

extra:
  recipe-maintainers:
    - bollwyvl
